INSERT INTO public.categories (id, name, "parentId") VALUES (1, 'Копирайт', null);
INSERT INTO public.categories (id, name, "parentId") VALUES (2, 'Автомобили', 1);
INSERT INTO public.categories (id, name, "parentId") VALUES (3, 'Автомобили', 2);
INSERT INTO public.categories (id, name, "parentId") VALUES (4, 'Автозвук', 2);
INSERT INTO public.categories (id, name, "parentId") VALUES (5, 'Автопробеги/Автошоу', 2);
INSERT INTO public.categories (id, name, "parentId") VALUES (6, 'Автосервис', 2);
INSERT INTO public.categories (id, name, "parentId") VALUES (7, 'Автохимия', 2);
INSERT INTO public.categories (id, name, "parentId") VALUES (8, 'Мотоциклы', 2);
INSERT INTO public.categories (id, name, "parentId") VALUES (9, 'Обзоры автомобилей', 2);
INSERT INTO public.categories (id, name, "parentId") VALUES (10, 'Спецтехника', 2);
INSERT INTO public.categories (id, name, "parentId") VALUES (11, 'Тюнинг', 2);
INSERT INTO public.categories (id, name, "parentId") VALUES (12, 'Бизнес', 1);
INSERT INTO public.categories (id, name, "parentId") VALUES (13, 'GR/Правовое регулирование', 12);
INSERT INTO public.categories (id, name, "parentId") VALUES (14, 'PR', 12);
INSERT INTO public.categories (id, name, "parentId") VALUES (15, 'Логистика', 12);
INSERT INTO public.categories (id, name, "parentId") VALUES (16, 'Малый бизнес', 12);
INSERT INTO public.categories (id, name, "parentId") VALUES (17, 'Маркетинг', 12);
INSERT INTO public.categories (id, name, "parentId") VALUES (18, 'Менеджмент', 12);
INSERT INTO public.categories (id, name, "parentId") VALUES (19, 'Тайм-менеджмент', 18);
INSERT INTO public.categories (id, name, "parentId") VALUES (20, 'Партнерские отношения', 12);
INSERT INTO public.categories (id, name, "parentId") VALUES (21, 'Платежные системы', 12);
INSERT INTO public.categories (id, name, "parentId") VALUES (22, 'Криптовалюта', 21);
INSERT INTO public.categories (id, name, "parentId") VALUES (23, 'Бухгалтерия и финансы', 1);
INSERT INTO public.categories (id, name, "parentId") VALUES (24, 'Арендные отношения', 23);
INSERT INTO public.categories (id, name, "parentId") VALUES (25, 'Аудиторская деятельность', 23);
INSERT INTO public.categories (id, name, "parentId") VALUES (26, 'Банковская деятельность', 23);
INSERT INTO public.categories (id, name, "parentId") VALUES (27, 'Бухгалтерский учет', 23);
INSERT INTO public.categories (id, name, "parentId") VALUES (28, 'Кредитование', 23);
INSERT INTO public.categories (id, name, "parentId") VALUES (29, 'Личные финансы, сбережения', 23);
INSERT INTO public.categories (id, name, "parentId") VALUES (30, 'Налоги', 23);
INSERT INTO public.categories (id, name, "parentId") VALUES (31, 'Нормативные документы', 23);
INSERT INTO public.categories (id, name, "parentId") VALUES (32, 'Отчетность', 23);
INSERT INTO public.categories (id, name, "parentId") VALUES (33, 'Страхование', 23);
INSERT INTO public.categories (id, name, "parentId") VALUES (34, 'Финансы и инвестиции', 23);
INSERT INTO public.categories (id, name, "parentId") VALUES (35, 'Высокие технологии / IT', 1);
INSERT INTO public.categories (id, name, "parentId") VALUES (36, 'Android/iOS', 35);
INSERT INTO public.categories (id, name, "parentId") VALUES (37, 'Linux', 35);
INSERT INTO public.categories (id, name, "parentId") VALUES (38, 'Windows', 35);
INSERT INTO public.categories (id, name, "parentId") VALUES (39, 'Беспроводные технологии', 35);
INSERT INTO public.categories (id, name, "parentId") VALUES (40, 'Биотехнологии', 35);
INSERT INTO public.categories (id, name, "parentId") VALUES (41, 'Интернет-технологии', 35);
INSERT INTO public.categories (id, name, "parentId") VALUES (42, 'SMM, продвижение в соцсетях', 41);
INSERT INTO public.categories (id, name, "parentId") VALUES (43, 'Заработок в интернете', 41);
INSERT INTO public.categories (id, name, "parentId") VALUES (44, 'Интернет-маркетинг', 41);
INSERT INTO public.categories (id, name, "parentId") VALUES (45, 'Продвижение сайтов', 41);
INSERT INTO public.categories (id, name, "parentId") VALUES (46, 'Создание сайтов', 41);
INSERT INTO public.categories (id, name, "parentId") VALUES (47, 'Искусственный интеллект', 35);
INSERT INTO public.categories (id, name, "parentId") VALUES (48, 'Нанотехнологии', 35);
INSERT INTO public.categories (id, name, "parentId") VALUES (49, 'Программирование', 35);
INSERT INTO public.categories (id, name, "parentId") VALUES (50, 'Программное обеспечение', 49);
INSERT INTO public.categories (id, name, "parentId") VALUES (51, 'Робототехника', 35);
INSERT INTO public.categories (id, name, "parentId") VALUES (52, 'Системное администрирование', 35);
INSERT INTO public.categories (id, name, "parentId") VALUES (53, 'Живая природа/Растительный мир', 1);
INSERT INTO public.categories (id, name, "parentId") VALUES (54, 'Животные', 53);
INSERT INTO public.categories (id, name, "parentId") VALUES (55, 'Насекомые', 53);
INSERT INTO public.categories (id, name, "parentId") VALUES (56, 'Охота', 53);
INSERT INTO public.categories (id, name, "parentId") VALUES (57, 'Охотничье оружие', 56);
INSERT INTO public.categories (id, name, "parentId") VALUES (58, 'Природный ландшафт', 53);
INSERT INTO public.categories (id, name, "parentId") VALUES (59, 'Птицы', 53);
INSERT INTO public.categories (id, name, "parentId") VALUES (60, 'Растения', 53);
INSERT INTO public.categories (id, name, "parentId") VALUES (61, 'Рыбалка', 53);
INSERT INTO public.categories (id, name, "parentId") VALUES (62, 'Экология', 53);
INSERT INTO public.categories (id, name, "parentId") VALUES (63, 'Журналистика', 1);
INSERT INTO public.categories (id, name, "parentId") VALUES (64, 'Журналистская этика', 63);
INSERT INTO public.categories (id, name, "parentId") VALUES (65, 'Издательство и полиграфия', 63);
INSERT INTO public.categories (id, name, "parentId") VALUES (66, 'СМИ и периодика', 63);
INSERT INTO public.categories (id, name, "parentId") VALUES (67, 'Закон и право', 1);
INSERT INTO public.categories (id, name, "parentId") VALUES (68, 'Арбитраж', 67);
INSERT INTO public.categories (id, name, "parentId") VALUES (69, 'Законодательство', 67);
INSERT INTO public.categories (id, name, "parentId") VALUES (70, 'Криминалистика', 67);
INSERT INTO public.categories (id, name, "parentId") VALUES (71, 'Нормативные, законодательные базы', 67);
INSERT INTO public.categories (id, name, "parentId") VALUES (72, 'Юридические услуги', 67);
INSERT INTO public.categories (id, name, "parentId") VALUES (73, 'Интересное', 1);
INSERT INTO public.categories (id, name, "parentId") VALUES (74, 'Астрология', 73);
INSERT INTO public.categories (id, name, "parentId") VALUES (75, 'Гадания, предсказания, магия', 73);
INSERT INTO public.categories (id, name, "parentId") VALUES (76, 'Народные поверья', 73);
INSERT INTO public.categories (id, name, "parentId") VALUES (77, 'Необъяснимо, но факт', 73);
INSERT INTO public.categories (id, name, "parentId") VALUES (78, 'Происшествия', 73);
INSERT INTO public.categories (id, name, "parentId") VALUES (79, 'Развлечения', 73);
INSERT INTO public.categories (id, name, "parentId") VALUES (80, 'Игры', 79);
INSERT INTO public.categories (id, name, "parentId") VALUES (81, 'MMO', 80);
INSERT INTO public.categories (id, name, "parentId") VALUES (82, 'Азартные игры', 80);
INSERT INTO public.categories (id, name, "parentId") VALUES (83, 'Карточные игры', 80);
INSERT INTO public.categories (id, name, "parentId") VALUES (84, 'Компьютерные игры', 80);
INSERT INTO public.categories (id, name, "parentId") VALUES (85, 'MMORPG', 84);
INSERT INTO public.categories (id, name, "parentId") VALUES (86, 'Разное', 73);
INSERT INTO public.categories (id, name, "parentId") VALUES (87, 'Случаи из жизни', 73);
INSERT INTO public.categories (id, name, "parentId") VALUES (88, 'Фэншуй', 73);
INSERT INTO public.categories (id, name, "parentId") VALUES (89, 'Хобби и увлечения', 73);
INSERT INTO public.categories (id, name, "parentId") VALUES (90, 'Вышивка', 89);
INSERT INTO public.categories (id, name, "parentId") VALUES (91, 'Коллекционирование', 89);
INSERT INTO public.categories (id, name, "parentId") VALUES (92, 'Коллекционное оружие', 91);
INSERT INTO public.categories (id, name, "parentId") VALUES (93, 'Рукоделие', 89);
INSERT INTO public.categories (id, name, "parentId") VALUES (94, 'Вязание крючком', 93);
INSERT INTO public.categories (id, name, "parentId") VALUES (95, 'Вязание спицами', 93);
INSERT INTO public.categories (id, name, "parentId") VALUES (96, 'Декор', 93);
INSERT INTO public.categories (id, name, "parentId") VALUES (97, 'Работы из бисера', 93);
INSERT INTO public.categories (id, name, "parentId") VALUES (98, 'Цветоводство', 89);
INSERT INTO public.categories (id, name, "parentId") VALUES (99, 'Юмор', 73);
INSERT INTO public.categories (id, name, "parentId") VALUES (100, 'История', 1);
INSERT INTO public.categories (id, name, "parentId") VALUES (101, 'Войны', 100);
INSERT INTO public.categories (id, name, "parentId") VALUES (102, 'Военная техника', 101);
INSERT INTO public.categories (id, name, "parentId") VALUES (103, 'Боевое оружие', 101);
INSERT INTO public.categories (id, name, "parentId") VALUES (104, 'Холодное оружие', 101);
INSERT INTO public.categories (id, name, "parentId") VALUES (105, 'Исторические памятники', 100);
INSERT INTO public.categories (id, name, "parentId") VALUES (106, 'Этапы развития', 100);
INSERT INTO public.categories (id, name, "parentId") VALUES (107, 'Красота и здоровье', 1);
INSERT INTO public.categories (id, name, "parentId") VALUES (108, 'Косметические и ухаживающие средства', 107);
INSERT INTO public.categories (id, name, "parentId") VALUES (109, 'Косметические процедуры', 107);
INSERT INTO public.categories (id, name, "parentId") VALUES (110, 'Макияж', 107);
INSERT INTO public.categories (id, name, "parentId") VALUES (111, 'Рецепты красоты', 107);
INSERT INTO public.categories (id, name, "parentId") VALUES (112, 'Уход за волосами', 107);
INSERT INTO public.categories (id, name, "parentId") VALUES (113, 'Уход за лицом', 107);
INSERT INTO public.categories (id, name, "parentId") VALUES (114, 'Уход за телом', 107);
INSERT INTO public.categories (id, name, "parentId") VALUES (115, 'Кулинария', 1);
INSERT INTO public.categories (id, name, "parentId") VALUES (116, 'Национальные кухни', 115);
INSERT INTO public.categories (id, name, "parentId") VALUES (117, 'Питание/Диеты', 115);
INSERT INTO public.categories (id, name, "parentId") VALUES (118, 'Продукты', 115);
INSERT INTO public.categories (id, name, "parentId") VALUES (119, 'Рецепты', 115);
INSERT INTO public.categories (id, name, "parentId") VALUES (120, 'Культура', 1);
INSERT INTO public.categories (id, name, "parentId") VALUES (121, 'Живопись', 120);
INSERT INTO public.categories (id, name, "parentId") VALUES (122, 'Кино и телевидение', 120);
INSERT INTO public.categories (id, name, "parentId") VALUES (123, 'Мультипликация', 122);
INSERT INTO public.categories (id, name, "parentId") VALUES (124, 'Культуры разных стран', 120);
INSERT INTO public.categories (id, name, "parentId") VALUES (125, 'Литература', 120);
INSERT INTO public.categories (id, name, "parentId") VALUES (126, 'Басни, сказки, легенды', 125);
INSERT INTO public.categories (id, name, "parentId") VALUES (127, 'Загадки', 125);
INSERT INTO public.categories (id, name, "parentId") VALUES (128, 'Стихи', 125);
INSERT INTO public.categories (id, name, "parentId") VALUES (129, 'Тексты песен', 125);
INSERT INTO public.categories (id, name, "parentId") VALUES (130, 'Музыка', 120);
INSERT INTO public.categories (id, name, "parentId") VALUES (131, 'Памятники культуры', 120);
INSERT INTO public.categories (id, name, "parentId") VALUES (132, 'Театр', 120);
INSERT INTO public.categories (id, name, "parentId") VALUES (133, 'Философия', 120);
INSERT INTO public.categories (id, name, "parentId") VALUES (134, 'Жизнь и философия', 133);
INSERT INTO public.categories (id, name, "parentId") VALUES (135, 'Знаменитые философы', 133);
INSERT INTO public.categories (id, name, "parentId") VALUES (136, 'Источники философии', 133);
INSERT INTO public.categories (id, name, "parentId") VALUES (137, 'Философские направления и школы', 133);
INSERT INTO public.categories (id, name, "parentId") VALUES (138, 'Фотография', 120);
INSERT INTO public.categories (id, name, "parentId") VALUES (139, 'Мебель', 1);
INSERT INTO public.categories (id, name, "parentId") VALUES (140, 'Медицина/Здоровье', 1);
INSERT INTO public.categories (id, name, "parentId") VALUES (141, 'Анатомия', 140);
INSERT INTO public.categories (id, name, "parentId") VALUES (142, 'Беременность и роды', 140);
INSERT INTO public.categories (id, name, "parentId") VALUES (143, 'Ветеринария', 140);
INSERT INTO public.categories (id, name, "parentId") VALUES (144, 'Заболевания', 140);
INSERT INTO public.categories (id, name, "parentId") VALUES (145, 'Йога/Лечебная гимнастика', 140);
INSERT INTO public.categories (id, name, "parentId") VALUES (146, 'Массаж', 140);
INSERT INTO public.categories (id, name, "parentId") VALUES (147, 'Медицинская этика/Медицинское законодательство', 140);
INSERT INTO public.categories (id, name, "parentId") VALUES (148, 'Медицинское оборудование/Медицинские технологии', 140);
INSERT INTO public.categories (id, name, "parentId") VALUES (149, 'Методики лечения', 140);
INSERT INTO public.categories (id, name, "parentId") VALUES (150, 'Народная медицина', 140);
INSERT INTO public.categories (id, name, "parentId") VALUES (151, 'Парфюмерия и ароматерапия', 140);
INSERT INTO public.categories (id, name, "parentId") VALUES (152, 'Питание/Диеты', 140);
INSERT INTO public.categories (id, name, "parentId") VALUES (153, 'Пластическая хирургия, косметическая хирургия', 140);
INSERT INTO public.categories (id, name, "parentId") VALUES (154, 'Сауна/Баня', 140);
INSERT INTO public.categories (id, name, "parentId") VALUES (155, 'Стоматология', 140);
INSERT INTO public.categories (id, name, "parentId") VALUES (156, 'Фармакология', 140);
INSERT INTO public.categories (id, name, "parentId") VALUES (157, 'Мода и стиль', 1);
INSERT INTO public.categories (id, name, "parentId") VALUES (158, 'Аксессуары', 157);
INSERT INTO public.categories (id, name, "parentId") VALUES (159, 'Бренды', 157);
INSERT INTO public.categories (id, name, "parentId") VALUES (160, 'Детская мода  ', 157);
INSERT INTO public.categories (id, name, "parentId") VALUES (161, 'Дизайнеры/Бутики', 157);
INSERT INTO public.categories (id, name, "parentId") VALUES (162, 'Модели', 157);
INSERT INTO public.categories (id, name, "parentId") VALUES (163, 'Модные тенденции', 157);
INSERT INTO public.categories (id, name, "parentId") VALUES (164, 'Обувь', 157);
INSERT INTO public.categories (id, name, "parentId") VALUES (165, 'Одежда', 157);
INSERT INTO public.categories (id, name, "parentId") VALUES (166, 'Показы мод/Модные мероприятия', 157);
INSERT INTO public.categories (id, name, "parentId") VALUES (167, 'Недвижимость', 1);
INSERT INTO public.categories (id, name, "parentId") VALUES (168, 'Аренда недвижимости', 167);
INSERT INTO public.categories (id, name, "parentId") VALUES (169, 'Коммерческая недвижимость', 167);
INSERT INTO public.categories (id, name, "parentId") VALUES (170, 'Купля-продажа недвижимости', 167);
INSERT INTO public.categories (id, name, "parentId") VALUES (171, 'Образование', 1);
INSERT INTO public.categories (id, name, "parentId") VALUES (172, 'Гуманитарные науки', 171);
INSERT INTO public.categories (id, name, "parentId") VALUES (173, 'История', 172);
INSERT INTO public.categories (id, name, "parentId") VALUES (174, 'Языкознание', 172);
INSERT INTO public.categories (id, name, "parentId") VALUES (175, 'Естественные науки', 171);
INSERT INTO public.categories (id, name, "parentId") VALUES (176, 'Астрономия, космос', 175);
INSERT INTO public.categories (id, name, "parentId") VALUES (177, 'Биология', 175);
INSERT INTO public.categories (id, name, "parentId") VALUES (178, 'География', 175);
INSERT INTO public.categories (id, name, "parentId") VALUES (179, 'Физика', 175);
INSERT INTO public.categories (id, name, "parentId") VALUES (180, 'Химия', 175);
INSERT INTO public.categories (id, name, "parentId") VALUES (181, 'Точные науки', 171);
INSERT INTO public.categories (id, name, "parentId") VALUES (182, 'Алгебра  ', 181);
INSERT INTO public.categories (id, name, "parentId") VALUES (183, 'Геометрия', 181);
INSERT INTO public.categories (id, name, "parentId") VALUES (184, 'Языки', 171);
INSERT INTO public.categories (id, name, "parentId") VALUES (185, 'Переводы', 184);
INSERT INTO public.categories (id, name, "parentId") VALUES (186, 'Языковедение', 184);
INSERT INTO public.categories (id, name, "parentId") VALUES (187, 'Общество', 1);
INSERT INTO public.categories (id, name, "parentId") VALUES (188, 'Дом и семья', 187);
INSERT INTO public.categories (id, name, "parentId") VALUES (189, 'Бытовые услуги', 188);
INSERT INTO public.categories (id, name, "parentId") VALUES (190, 'Дети/Воспитание детей', 188);
INSERT INTO public.categories (id, name, "parentId") VALUES (191, 'Дети и Воспитание детей от 0 до 3 лет', 190);
INSERT INTO public.categories (id, name, "parentId") VALUES (192, 'Дети и воспитание детей от 3 до 7 лет', 190);
INSERT INTO public.categories (id, name, "parentId") VALUES (193, 'Дети и детский сад', 190);
INSERT INTO public.categories (id, name, "parentId") VALUES (194, 'Дети и школа', 190);
INSERT INTO public.categories (id, name, "parentId") VALUES (195, 'Переходный возраст', 190);
INSERT INTO public.categories (id, name, "parentId") VALUES (196, 'Домашнее хозяйство', 188);
INSERT INTO public.categories (id, name, "parentId") VALUES (197, 'Домашние питомцы', 188);
INSERT INTO public.categories (id, name, "parentId") VALUES (198, 'Домашний интерьер', 188);
INSERT INTO public.categories (id, name, "parentId") VALUES (199, 'Полезные советы', 188);
INSERT INTO public.categories (id, name, "parentId") VALUES (200, 'Полезные советы для дома', 199);
INSERT INTO public.categories (id, name, "parentId") VALUES (201, 'Сад/Огород', 188);
INSERT INTO public.categories (id, name, "parentId") VALUES (202, 'Семейные отношения', 188);
INSERT INTO public.categories (id, name, "parentId") VALUES (203, 'Товары для детей', 188);
INSERT INTO public.categories (id, name, "parentId") VALUES (204, 'Товары для дома', 188);
INSERT INTO public.categories (id, name, "parentId") VALUES (205, 'Знаменитости', 187);
INSERT INTO public.categories (id, name, "parentId") VALUES (206, 'Иммиграция', 187);
INSERT INTO public.categories (id, name, "parentId") VALUES (207, 'Политика', 187);
INSERT INTO public.categories (id, name, "parentId") VALUES (208, 'Работа, карьера', 187);
INSERT INTO public.categories (id, name, "parentId") VALUES (209, 'Трудоустройство/Поиск работы', 208);
INSERT INTO public.categories (id, name, "parentId") VALUES (210, 'Религия', 187);
INSERT INTO public.categories (id, name, "parentId") VALUES (211, 'Христианство', 210);
INSERT INTO public.categories (id, name, "parentId") VALUES (212, 'Экономика', 187);
INSERT INTO public.categories (id, name, "parentId") VALUES (213, 'Отдых и Туризм', 1);
INSERT INTO public.categories (id, name, "parentId") VALUES (214, 'Активный отдых', 213);
INSERT INTO public.categories (id, name, "parentId") VALUES (215, 'Гастрономический туризм', 213);
INSERT INTO public.categories (id, name, "parentId") VALUES (216, 'Гостиницы/Отели', 213);
INSERT INTO public.categories (id, name, "parentId") VALUES (217, 'Достопримечательности', 213);
INSERT INTO public.categories (id, name, "parentId") VALUES (218, 'Обзор стран и городов', 213);
INSERT INTO public.categories (id, name, "parentId") VALUES (219, 'Отдых в России', 213);
INSERT INTO public.categories (id, name, "parentId") VALUES (220, 'Отдых в странах Африки', 213);
INSERT INTO public.categories (id, name, "parentId") VALUES (221, 'Отдых в странах Европы', 213);
INSERT INTO public.categories (id, name, "parentId") VALUES (222, 'Отдых в странах СНГ', 213);
INSERT INTO public.categories (id, name, "parentId") VALUES (223, 'Побережье городов', 213);
INSERT INTO public.categories (id, name, "parentId") VALUES (224, 'Путешествия/Туры', 213);
INSERT INTO public.categories (id, name, "parentId") VALUES (225, 'Праздники', 1);
INSERT INTO public.categories (id, name, "parentId") VALUES (226, 'Карнавальные костюмы', 225);
INSERT INTO public.categories (id, name, "parentId") VALUES (227, 'Новый год', 225);
INSERT INTO public.categories (id, name, "parentId") VALUES (228, 'Подарки и поздравления', 225);
INSERT INTO public.categories (id, name, "parentId") VALUES (229, 'Свадьба', 225);
INSERT INTO public.categories (id, name, "parentId") VALUES (230, 'Семейный отдых/Семейные праздники', 225);
INSERT INTO public.categories (id, name, "parentId") VALUES (231, 'Сценарий мероприятия', 225);
INSERT INTO public.categories (id, name, "parentId") VALUES (232, 'Промышленность и производство', 1);
INSERT INTO public.categories (id, name, "parentId") VALUES (233, 'Авиация/космонавтика', 232);
INSERT INTO public.categories (id, name, "parentId") VALUES (234, 'Оборонные технологии', 232);
INSERT INTO public.categories (id, name, "parentId") VALUES (235, 'Промышленное оборудование', 232);
INSERT INTO public.categories (id, name, "parentId") VALUES (236, 'Системы безопасности, контроля, автоматизации', 232);
INSERT INTO public.categories (id, name, "parentId") VALUES (237, 'Энергетика', 232);
INSERT INTO public.categories (id, name, "parentId") VALUES (238, 'Психология', 1);
INSERT INTO public.categories (id, name, "parentId") VALUES (239, 'Женская психология', 238);
INSERT INTO public.categories (id, name, "parentId") VALUES (240, 'Мужская психология', 238);
INSERT INTO public.categories (id, name, "parentId") VALUES (241, 'Научно-популярная психология', 238);
INSERT INTO public.categories (id, name, "parentId") VALUES (242, 'Практическая психология', 238);
INSERT INTO public.categories (id, name, "parentId") VALUES (243, 'Психология в разных сферах жизни', 238);
INSERT INTO public.categories (id, name, "parentId") VALUES (244, 'Психология общения', 238);
INSERT INTO public.categories (id, name, "parentId") VALUES (245, 'Психология семейных отношений/Психология любви', 238);
INSERT INTO public.categories (id, name, "parentId") VALUES (246, 'Самосовершенствование', 238);
INSERT INTO public.categories (id, name, "parentId") VALUES (247, 'Тренинги/Тесты', 238);
INSERT INTO public.categories (id, name, "parentId") VALUES (248, 'Эзотерика', 238);
INSERT INTO public.categories (id, name, "parentId") VALUES (249, 'Мистика', 248);
INSERT INTO public.categories (id, name, "parentId") VALUES (250, 'Реклама', 1);
INSERT INTO public.categories (id, name, "parentId") VALUES (251, 'Наружная реклама', 250);
INSERT INTO public.categories (id, name, "parentId") VALUES (252, 'Полиграфия', 250);
INSERT INTO public.categories (id, name, "parentId") VALUES (253, 'Рекламные конструкции', 250);
INSERT INTO public.categories (id, name, "parentId") VALUES (254, 'Сувенирная продукция', 250);
INSERT INTO public.categories (id, name, "parentId") VALUES (255, 'Секс (18+)', 1);
INSERT INTO public.categories (id, name, "parentId") VALUES (256, 'Сельское хозяйство', 1);
INSERT INTO public.categories (id, name, "parentId") VALUES (257, 'Пчеловодство', 256);
INSERT INTO public.categories (id, name, "parentId") VALUES (258, 'Сельскохозяйственная техника', 256);
INSERT INTO public.categories (id, name, "parentId") VALUES (259, 'Спорт', 1);
INSERT INTO public.categories (id, name, "parentId") VALUES (260, 'Букмекерство', 259);
INSERT INTO public.categories (id, name, "parentId") VALUES (261, 'Виды спорта', 259);
INSERT INTO public.categories (id, name, "parentId") VALUES (262, 'Соревнования/Чемпионаты', 259);
INSERT INTO public.categories (id, name, "parentId") VALUES (263, 'Чемпионат мира по футболу', 262);
INSERT INTO public.categories (id, name, "parentId") VALUES (264, 'Спорт и здоровье', 259);
INSERT INTO public.categories (id, name, "parentId") VALUES (265, 'Снижение веса и похудение', 264);
INSERT INTO public.categories (id, name, "parentId") VALUES (266, 'Спортивное оружие', 259);
INSERT INTO public.categories (id, name, "parentId") VALUES (267, 'Спортивное питание', 259);
INSERT INTO public.categories (id, name, "parentId") VALUES (268, 'Спортивное снаряжение/Спортивная форма', 259);
INSERT INTO public.categories (id, name, "parentId") VALUES (269, 'Спортсмены/Тренеры/Комментаторы', 259);
INSERT INTO public.categories (id, name, "parentId") VALUES (270, 'Строительство', 1);
INSERT INTO public.categories (id, name, "parentId") VALUES (271, 'Архитектура', 270);
INSERT INTO public.categories (id, name, "parentId") VALUES (272, 'Дизайн помещений', 270);
INSERT INTO public.categories (id, name, "parentId") VALUES (273, 'Ландшафтный дизайн', 270);
INSERT INTO public.categories (id, name, "parentId") VALUES (274, 'Ремонт', 270);
INSERT INTO public.categories (id, name, "parentId") VALUES (275, 'Сантехника', 270);
INSERT INTO public.categories (id, name, "parentId") VALUES (276, 'Стройматериалы', 270);
INSERT INTO public.categories (id, name, "parentId") VALUES (277, 'Технологии', 270);
INSERT INTO public.categories (id, name, "parentId") VALUES (278, 'Техника', 1);
INSERT INTO public.categories (id, name, "parentId") VALUES (279, 'Аудиотехника', 278);
INSERT INTO public.categories (id, name, "parentId") VALUES (280, 'Бытовая техника', 278);
INSERT INTO public.categories (id, name, "parentId") VALUES (281, 'Водная техника', 278);
INSERT INTO public.categories (id, name, "parentId") VALUES (282, 'Вычислительная техника', 278);
INSERT INTO public.categories (id, name, "parentId") VALUES (283, 'Мобильные телефоны', 278);
INSERT INTO public.categories (id, name, "parentId") VALUES (284, 'Промышленная техника', 278);
INSERT INTO public.categories (id, name, "parentId") VALUES (285, 'Радиоэлектроника', 278);
INSERT INTO public.categories (id, name, "parentId") VALUES (286, 'Светотехника', 278);
INSERT INTO public.categories (id, name, "parentId") VALUES (287, 'Транспорт', 278);
INSERT INTO public.categories (id, name, "parentId") VALUES (288, 'Фототехника', 278);
INSERT INTO public.categories (id, name, "parentId") VALUES (289, 'Электрика', 278);
INSERT INTO public.categories (id, name, "parentId") VALUES (290, 'Электротехника', 278);
INSERT INTO public.categories (id, name, "parentId") VALUES (291, 'Услуги', 1);
INSERT INTO public.categories (id, name, "parentId") VALUES (292, 'Фондовый рынок', 1);
INSERT INTO public.categories (id, name, "parentId") VALUES (293, 'Инвестиционный рынок/Инвестиционные компании', 292);
INSERT INTO public.categories (id, name, "parentId") VALUES (294, 'Рынок ценных бумаг', 292);
INSERT INTO public.categories (id, name, "parentId") VALUES (295, 'Торговые системы', 292);
INSERT INTO public.categories (id, name, "parentId") VALUES (296, 'Трейдинг/Интернет-трейдинг', 292);
INSERT INTO public.categories (id, name, "parentId") VALUES (297, 'Форекс', 292);
INSERT INTO public.categories (id, name, "parentId") VALUES (298, 'Ценообразование на рынке/Курсы валют', 292);
INSERT INTO public.categories (id, name, "parentId") VALUES (299, 'Шитье', 1);
INSERT INTO public.categories (id, name, "parentId") VALUES (300, 'Фото', null);
INSERT INTO public.categories (id, name, "parentId") VALUES (301, 'Архитектура', 300);
INSERT INTO public.categories (id, name, "parentId") VALUES (302, 'Бизнес/Финансы', 300);
INSERT INTO public.categories (id, name, "parentId") VALUES (303, 'Векторы/Графика', 300);
INSERT INTO public.categories (id, name, "parentId") VALUES (304, 'Виды городов', 300);
INSERT INTO public.categories (id, name, "parentId") VALUES (305, 'Еда/Напитки', 300);
INSERT INTO public.categories (id, name, "parentId") VALUES (306, 'Здоровье/Медицина', 300);
INSERT INTO public.categories (id, name, "parentId") VALUES (307, 'Знаки/Символы', 300);
INSERT INTO public.categories (id, name, "parentId") VALUES (308, 'Интерьеры/Декорации', 300);
INSERT INTO public.categories (id, name, "parentId") VALUES (309, 'Дизайн помещений', 308);
INSERT INTO public.categories (id, name, "parentId") VALUES (310, 'Ландшафтный дизайн', 308);
INSERT INTO public.categories (id, name, "parentId") VALUES (312, 'Искусство', 300);
INSERT INTO public.categories (id, name, "parentId") VALUES (313, 'Абстракция', 312);
INSERT INTO public.categories (id, name, "parentId") VALUES (314, 'Натюрморт', 312);
INSERT INTO public.categories (id, name, "parentId") VALUES (315, 'Красота/Мода', 300);
INSERT INTO public.categories (id, name, "parentId") VALUES (316, 'Люди', 300);
INSERT INTO public.categories (id, name, "parentId") VALUES (317, 'Мастер-классы/Hand-made', 300);
INSERT INTO public.categories (id, name, "parentId") VALUES (318, 'Коллаж', 317);
INSERT INTO public.categories (id, name, "parentId") VALUES (319, 'Наука/Образование', 300);
INSERT INTO public.categories (id, name, "parentId") VALUES (320, 'Музеи', 319);
INSERT INTO public.categories (id, name, "parentId") VALUES (321, 'Объекты/Предметы', 300);
INSERT INTO public.categories (id, name, "parentId") VALUES (322, 'Отдых', 300);
INSERT INTO public.categories (id, name, "parentId") VALUES (323, 'Праздники/Развлечения', 300);
INSERT INTO public.categories (id, name, "parentId") VALUES (324, 'Новый год', 323);
INSERT INTO public.categories (id, name, "parentId") VALUES (325, 'Свадьба', 323);
INSERT INTO public.categories (id, name, "parentId") VALUES (326, 'Природа', 300);
INSERT INTO public.categories (id, name, "parentId") VALUES (327, 'Грибы', 326);
INSERT INTO public.categories (id, name, "parentId") VALUES (328, 'Животные', 326);
INSERT INTO public.categories (id, name, "parentId") VALUES (329, 'Насекомые', 326);
INSERT INTO public.categories (id, name, "parentId") VALUES (330, 'Парки', 326);
INSERT INTO public.categories (id, name, "parentId") VALUES (331, 'Пейзажи', 326);
INSERT INTO public.categories (id, name, "parentId") VALUES (332, 'Пляжи', 326);
INSERT INTO public.categories (id, name, "parentId") VALUES (333, 'Птицы', 326);
INSERT INTO public.categories (id, name, "parentId") VALUES (334, 'Растения', 326);
INSERT INTO public.categories (id, name, "parentId") VALUES (335, 'Цветы', 334);
INSERT INTO public.categories (id, name, "parentId") VALUES (336, 'Сад/Огород', 326);
INSERT INTO public.categories (id, name, "parentId") VALUES (337, 'Промышленность', 300);
INSERT INTO public.categories (id, name, "parentId") VALUES (338, 'Промышленная техника', 300);
INSERT INTO public.categories (id, name, "parentId") VALUES (339, 'Разное', 300);
INSERT INTO public.categories (id, name, "parentId") VALUES (340, 'Спорт', 300);
INSERT INTO public.categories (id, name, "parentId") VALUES (341, 'Строительство', 300);
INSERT INTO public.categories (id, name, "parentId") VALUES (342, 'Строительная техника', 341);
INSERT INTO public.categories (id, name, "parentId") VALUES (343, 'Строительные материалы и конструкции', 341);
INSERT INTO public.categories (id, name, "parentId") VALUES (344, 'Текстуры/Фоны', 300);
INSERT INTO public.categories (id, name, "parentId") VALUES (345, 'Техника', 300);
INSERT INTO public.categories (id, name, "parentId") VALUES (346, 'Транспорт', 300);
INSERT INTO public.categories (id, name, "parentId") VALUES (347, 'Водный транспорт', 346);
INSERT INTO public.categories (id, name, "parentId") VALUES (348, 'Грузовой транспорт', 346);
INSERT INTO public.categories (id, name, "parentId") VALUES (349, 'Легковые автомобили', 346);
INSERT INTO public.categories (id, name, "parentId") VALUES (350, 'Хобби', 300);
INSERT INTO public.categories (id, name, "parentId") VALUES (351, 'Аквариумистика', 300);
INSERT INTO public.categories (id, name, "parentId") VALUES (352, 'Охота', 300);
INSERT INTO public.categories (id, name, "parentId") VALUES (353, 'Рыбалка', 300);
INSERT INTO public.categories (id, name, "parentId") VALUES (354, 'Террариумистика', 300);
INSERT INTO public.categories (id, name, "parentId") VALUES (355, 'Видео', null);
INSERT INTO public.categories (id, name, "parentId") VALUES (356, 'Архитектура', 355);
INSERT INTO public.categories (id, name, "parentId") VALUES (357, 'Бизнес/Финансы', 355);
INSERT INTO public.categories (id, name, "parentId") VALUES (358, 'Векторы/Графика', 355);
INSERT INTO public.categories (id, name, "parentId") VALUES (359, 'Виды городов', 355);
INSERT INTO public.categories (id, name, "parentId") VALUES (360, 'Еда/Напитки', 355);
INSERT INTO public.categories (id, name, "parentId") VALUES (361, 'Здоровье/Медицина', 355);
INSERT INTO public.categories (id, name, "parentId") VALUES (362, 'Знаки/Символы', 355);
INSERT INTO public.categories (id, name, "parentId") VALUES (363, 'Интерьеры/Декорации', 355);
INSERT INTO public.categories (id, name, "parentId") VALUES (364, 'Дизайн помещений', 363);
INSERT INTO public.categories (id, name, "parentId") VALUES (365, 'Ландшафтный дизайн', 363);
INSERT INTO public.categories (id, name, "parentId") VALUES (366, 'Искусство', 355);
INSERT INTO public.categories (id, name, "parentId") VALUES (367, 'Абстракция', 366);
INSERT INTO public.categories (id, name, "parentId") VALUES (368, 'Натюрморт', 366);
INSERT INTO public.categories (id, name, "parentId") VALUES (369, 'Красота/Мода', 355);
INSERT INTO public.categories (id, name, "parentId") VALUES (370, 'Люди', 355);
INSERT INTO public.categories (id, name, "parentId") VALUES (371, 'Мастер-классы/Hand-made', 355);
INSERT INTO public.categories (id, name, "parentId") VALUES (372, 'Коллаж', 371);
INSERT INTO public.categories (id, name, "parentId") VALUES (373, 'Наука/Образование', 355);
INSERT INTO public.categories (id, name, "parentId") VALUES (374, 'Музеи', 373);
INSERT INTO public.categories (id, name, "parentId") VALUES (375, 'Объекты/Предметы', 355);
INSERT INTO public.categories (id, name, "parentId") VALUES (376, 'Отдых', 355);
INSERT INTO public.categories (id, name, "parentId") VALUES (377, 'Праздники/Развлечения', 355);
INSERT INTO public.categories (id, name, "parentId") VALUES (378, 'Новый год', 377);
INSERT INTO public.categories (id, name, "parentId") VALUES (379, 'Свадьба', 377);
INSERT INTO public.categories (id, name, "parentId") VALUES (380, 'Природа', 355);
INSERT INTO public.categories (id, name, "parentId") VALUES (381, 'Грибы', 380);
INSERT INTO public.categories (id, name, "parentId") VALUES (382, 'Животные', 380);
INSERT INTO public.categories (id, name, "parentId") VALUES (383, 'Насекомые', 380);
INSERT INTO public.categories (id, name, "parentId") VALUES (384, 'Парки', 380);
INSERT INTO public.categories (id, name, "parentId") VALUES (385, 'Пейзажи', 380);
INSERT INTO public.categories (id, name, "parentId") VALUES (386, 'Пляжи', 380);
INSERT INTO public.categories (id, name, "parentId") VALUES (387, 'Птицы', 380);
INSERT INTO public.categories (id, name, "parentId") VALUES (388, 'Растения', 380);
INSERT INTO public.categories (id, name, "parentId") VALUES (389, 'Цветы', 388);
INSERT INTO public.categories (id, name, "parentId") VALUES (390, 'Сад/Огород', 380);
INSERT INTO public.categories (id, name, "parentId") VALUES (391, 'Промышленность', 355);
INSERT INTO public.categories (id, name, "parentId") VALUES (392, 'Промышленная техника', 355);
INSERT INTO public.categories (id, name, "parentId") VALUES (393, 'Разное', 355);
INSERT INTO public.categories (id, name, "parentId") VALUES (394, 'Спорт', 355);
INSERT INTO public.categories (id, name, "parentId") VALUES (395, 'Строительство', 355);
INSERT INTO public.categories (id, name, "parentId") VALUES (396, 'Строительная техника', 395);
INSERT INTO public.categories (id, name, "parentId") VALUES (397, 'Строительные материалы и конструкции', 395);
INSERT INTO public.categories (id, name, "parentId") VALUES (398, 'Текстуры/Фоны', 355);
INSERT INTO public.categories (id, name, "parentId") VALUES (399, 'Техника', 355);
INSERT INTO public.categories (id, name, "parentId") VALUES (400, 'Транспорт', 355);
INSERT INTO public.categories (id, name, "parentId") VALUES (401, 'Водный транспорт', 400);
INSERT INTO public.categories (id, name, "parentId") VALUES (402, 'Грузовой транспорт', 400);
INSERT INTO public.categories (id, name, "parentId") VALUES (403, 'Легковые автомобили', 400);
INSERT INTO public.categories (id, name, "parentId") VALUES (404, 'Хобби', 355);
INSERT INTO public.categories (id, name, "parentId") VALUES (405, 'Аквариумистика', 404);
INSERT INTO public.categories (id, name, "parentId") VALUES (406, 'Охота', 404);
INSERT INTO public.categories (id, name, "parentId") VALUES (407, 'Рыбалка', 404);
INSERT INTO public.categories (id, name, "parentId") VALUES (408, 'Террариумистика', 404);