const CustomerErrors = {
  fio: "ФИО",
  login: "Логин",
  email: "Почта",
  phone: "Номер",
  position: "Должность",
  sign: "Подпись",
  rights_no: "Номер доверености",
  rights_date: "Дата выдачи доверености",
  rights_expire: "Срок действия доверености",
  kpp: "КПП",
  ogrn: "ОГРН",
  password: "Пароль",
  company_name: "Название компании",
  company_address: "Юридический адрес компании",
  company_real_address: "Фактический адрес компании",
  inn: "ИНН",
  bik: "БИК",
  сhecking_account: "Расчетный счет",
  bank_name: "Наиманование банка",
  corporate_account: "Корреспондентский счет",
  city: "Город",
  site: "Сайт"
};